"""Exit code descriptions for CMS jobs.

Maps HTCondor and WMCore exit codes to human-readable descriptions.
WM_JOB_ERROR_CODES is copied from WMCore/WMExceptions.py.
"""

# fmt: off
WM_JOB_ERROR_CODES = {
    0: "Success",
    -1: "Error return without specification.",
    1: "Job failed to bootstrap CMSSW; likely a worker node issue.",
    2: "Interrupt (ANSI).",
    4: "Illegal instruction (ANSI).",
    5: "Trace trap (POSIX).",
    6: "Abort (ANSI) or IOT trap (4.2BSD).",
    7: "BUS error (4.2BSD).",
    8: "Floating point exception (ANSI).",
    9: "killed, unblockable (POSIX) kill -9.",
    11: "segmentation violation (ANSI) (most likely user application crashed).",
    15: "Termination (ANSI).",
    24: "Soft CPU limit exceeded (4.2 BSD).",
    25: "File size limit exceeded (4.2 BSD).",
    30: "Power failure restart (System V.).",
    50: "Required application version not found at the site.",
    64: "I/O error: cannot open data file (SEAL).",
    65: "End of job from user application (CMSSW).",
    66: "Application exception.",
    70: "Invalid Arguments: Not all the required arguments for cmsRun is passed",
    71: "Failed to initiate Scram project",
    72: "Failed to enter Scram project directory",
    73: "Failed to get Scram runtime",
    74: "Unable to untar sandbox",
    81: "Job did not find functioning CMSSW on worker node.",
    84: "Job failed to open local and fallback files.",
    85: "Job failed to open local and fallback files.",
    90: "Application exception.",
    92: "Job failed to open local and fallback files.",
    126: "Permission problem or command is not an executable",
    127: "Command not found",
    129: "Hangup (POSIX).",
    132: "Illegal instruction (ANSI).",
    133: "Trace trap (POSIX).",
    134: "Abort (ANSI) or IOT trap (4.2 BSD) (most likely user application crashed).",
    135: "Bus error (4.2 BSD).",
    137: "SIGKILL; likely an unrelated batch system kill.",
    139: "Segmentation violation (ANSI).",
    143: "Termination (ANSI)(or incorporate in the msg text).",
    147: "Error during attempted file stageout.",
    151: "Error during attempted file stageout.",
    152: "CPU limit exceeded (4.2 BSD).",
    153: "File size limit exceeded (4.2 BSD).",
    155: "Profiling alarm clock (4.2 BSD).",
    195: "Job did not produce a FJR; will retry.",
    243: "Timeout during attempted file stageout.",
    7000: "Exception from command line processing.",
    7001: "Configuration File Not Found.",
    7002: "Configuration File Read Error.",
    8001: "Other CMS Exception.",
    8002: "std::exception (other than bad_alloc).",
    8003: "Unknown Exception.",
    8004: "std::bad_alloc (memory exhaustion).",
    8005: "Bad Exception Type (e.g throwing a string).",
    8006: "ProductNotFound.",
    8007: "DictionaryNotFound.",
    8008: "InsertFailure.",
    8009: "Configuration.",
    8010: "LogicError.",
    8011: "UnimplementedFeature.",
    8012: "InvalidReference.",
    8013: "NullPointerError.",
    8014: "NoProductSpecified.",
    8015: "EventTimeout.",
    8016: "EventCorruption.",
    8017: "ScheduleExecutionFailure.",
    8018: "EventProcessorFailure.",
    8019: "FileInPathError.",
    8020: "FileOpenError (Likely a site error).",
    8021: "FileReadError (May be a site error).",
    8022: "FatalRootError.",
    8023: "MismatchedInputFiles.",
    8024: "ProductDoesNotSupportViews.",
    8025: "ProductDoesNotSupportPtr.",
    8026: "NotFound (something other than a product or dictionary not found).",
    8027: "FormatIncompatibility.",
    8028: "FileOpenError with fallback.",
    8029: "The job configuration has no input files specified for secondary input source.",
    8030: "Exceeded maximum allowed VSize (ExceededResourceVSize).",
    8031: "Exceeded maximum allowed RSS (ExceededResourceRSS).",
    8032: "Exceeded maximum allowed time (ExceededResourceTime).",
    8033: "Could not write output file (FileWriteError) (usually local disk problem).",
    8034: "FileNameInconsistentWithGUID",
    8501: "EventGenerationFailure",
    9000: "cmsRun caught (SIGINT and SIGUSR2) signal.",
    10031: "Directory VO_CMS_SW_DIR not found.",
    10032: "Failed to source CMS Environment setup script such as cmssset_default.sh, grid system or site equivalent script.",
    10034: "Required application version is not found at the site.",
    10040: "failed to generate cmsRun cfg file at runtime.",
    10042: "Unable to stage-in wrapper tarball.",
    10043: "Unable to bootstrap WMCore libraries (most likely site python is broken).",
    11001: "Error during job bootstrap: A sandbox must be specified",
    11002: "Error during job bootstrap: A job index must be specified",
    11003: "Error during job bootstrap: VO_CMS_SW_DIR, OSG_APP, CVMFS  or /cvmfs were not found.",
    11004: "Error during job bootstrap: job environment does not contain the init.sh script.",
    11005: "Error during job bootstrap: python isn't available on the worker node.",
    50110: "Executable file is not found.",
    50111: "Executable file has no exe permissions.",
    50113: "Executable did not get enough arguments.",
    50115: "cmsRun did not produce a valid job report at runtime (often means cmsRun segfaulted).",
    50116: "Could not determine exit code of cmsRun executable at runtime.",
    50513: "Failure to run SCRAM setup scripts.",
    50660: "Application terminated by wrapper because using too much RAM (PSS).",
    50662: "Application terminated by wrapper because using too much disk.",
    50664: "Application terminated by wrapper because using too much Wall Clock time.",
    50665: "Application terminated by wrapper because it stay idle too long.",
    50666: "Job removed by condor for unknown reasons.",
    50669: "Application terminated by wrapper for not defined reason.",
    60302: "Output file(s) not found.",
    60307: "General failure during files stage out.",
    60311: "Local Stage Out Failure using site specific plugin.",
    60312: "Failure in staging in log files during log collection (WMAgent).",
    60313: "Failed to clean up any files that were no longer needed (WMAgent).",
    60315: "StageOut initialisation error (Due to TFC, SITECONF etc).",
    60317: "Forced timeout for stuck stage out.",
    60318: "Internal error in Crab cmscp.py stageout script.",
    60319: "Failed to do AlcaHarvest stageout.",
    60320: "Failure to communicate with ASO server.",
    60321: "Site related issue: no space, SE down, refused connection.",
    60322: "User is not authorized to write to destination site.",
    60323: "User quota exceeded.",
    60324: "Other stageout exception.",
    60401: "Failure to assemble LFN in direct-to-merge (WMAgent).",
    60403: "Timeout during files stage out.",
    60404: "Timeout during staging of log archives- status unknown (WMAgent).",
    60405: "General failure to stage out log archives (WMAgent).",
    60407: "Timeout in staging in log files during log collection (WMAgent).",
    60408: "Failure to stage out of log files during log collection (WMAgent).",
    60409: "Timeout in stage out of log files during log collection (WMAgent).",
    60450: "No output files present in the report",
    60451: "Output file lacked adler32 checksum (WMAgent).",
    70318: "Failure in DQM upload.",
    70452: "No run/lumi information in file (WMAgent).",
    71101: "No sites are available to submit the job because the location of its input(s) do not pass the site whitelist/blacklist restrictions (WMAgent).",
    71102: "The job can only run at a site that is currently in Aborted state (WMAgent).",
    71103: "The job can run only at a site that is currently in Draining state (WMAgent).",
    71104: "JobSubmitter component could not find a job pickle object.",
    71105: "JobSubmitter component loaded an empty job pickle object.",
    71300: "The job was killed by the WMAgent, reason is unknown (WMAgent).",
    71301: "The job was killed by WMAgent because the site it was supposed to run at was set to Aborted (WMAgent).",
    71302: "The job was killed by WMAgent because the site it was supposed to run at was set to Draining (WMAgent).",
    71303: "The job was killed by WMAgent because the site it was supposed to run at was set to Down (WMAgent).",
    71304: "The job was killed by the WMAgent for using too much wallclock time (WMAgent) Job status was Running.",
    71305: "The job was killed by the WMAgent for using too much wallclock time (WMAgent) Job status was Pending.",
    71306: "The job was killed by the WMAgent for using too much wallclock time (WMAgent) Job status was Error.",
    71307: "The job was killed by the WMAgent for using too much wallclock time (WMAgent) Job status was Unkown.",
    80000: "Internal error in CRAB job wrapper.",
    80001: "No exit code set by job wrapper.",
    80453: "Unable to determine pset hash from output file (CRAB3).",
    90000: "Error in CRAB3 post-processing step (includes basically errors in stage out and file metadata upload).",
    99108: "Skipping this step due to a failure in a previous one.",
    99109: "Uncaught exception in WMAgent step executor.",
    99303: "Job failed and the original job report got lost",
    99304: "Could not find jobCache directory. Job will be failed",
    99305: "Found single input file with too many events to be processed in a pilot lifetime",
    99400: "Job is killed by condor_rm or SYSTEM_PERIODIC_REMOVE",
    99401: "Job is killed by unknown reason",
    99996: "Failed to find a step report in the worker node",
    99997: "Failed to load job report",
    99998: "Job report with size 0",
    99999: "Some generic error with the job report",
}
# fmt: on

SIGNALS = {
    1: "SIGHUP", 2: "SIGINT", 3: "SIGQUIT", 4: "SIGILL",
    6: "SIGABRT", 7: "SIGBUS", 8: "SIGFPE", 9: "SIGKILL",
    11: "SIGSEGV", 13: "SIGPIPE", 14: "SIGALRM", 15: "SIGTERM",
    24: "SIGXCPU", 25: "SIGXFSZ",
}


def describe(code_str):
    """Return description for an exit code string, or '' if unknown.

    Handles three formats:
    - "SIG:<N>" — signal kill (from ExitBySignal jobs)
    - "<N>" — integer code, looked up in WM_JOB_ERROR_CODES
    - anything else — empty string
    """
    if code_str.startswith("SIG:"):
        sig = int(code_str[4:])
        return "Killed by {}".format(SIGNALS.get(sig, "signal {}".format(sig)))
    try:
        return WM_JOB_ERROR_CODES.get(int(code_str), "")
    except (ValueError, TypeError):
        return ""
